# Generated by Django 3.2.13 on 2022-05-04 20:51

import dj_active_campaign.models
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ac_id', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='Active Campaign ID')),
                ('ac_title', models.CharField(max_length=50, verbose_name='Field Title')),
                ('ac_value', models.JSONField(blank=True, default=None, null=True, verbose_name='Field Value')),
                ('ac_type', models.CharField(choices=[('checkbox', 'Checkbox'), ('date', 'Date'), ('datetime', 'Datetime'), ('dropdown', 'Dropdown'), ('hidden', 'Hidden'), ('listbox', 'List Box'), ('NULL', 'Null'), ('radio', 'Radio'), ('text', 'Text'), ('textarea', 'Text Area')], default='text', max_length=50, verbose_name='Field Type')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('site', models.ForeignKey(default=dj_active_campaign.models.set_default_site_id, on_delete=django.db.models.deletion.CASCADE, related_name='ac_custom_field', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Custom Field',
                'verbose_name_plural': 'Custom Fields',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
